# Generated by Django 5.1.7 on 2025-06-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AFSC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_name', models.CharField(max_length=100, unique=True)),
                ('rank_level', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'Ranks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workcenter',
            fields=[
                ('workcenter_id', models.AutoField(primary_key=True, serialize=False)),
                ('workcenter_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Workcenter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CFETP',
            fields=[
                ('cfetp_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_number', models.CharField(max_length=10)),
                ('cfetp_name', models.CharField(max_length=100)),
                ('min_skill_level', models.IntegerField(choices=[(3, 'Apprentice'), (5, 'Journeyman'), (7, 'Craftsman'), (9, 'Superintendent')])),
                ('afsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.afsc')),
            ],
            options={
                'db_table': 'CFETP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MTL',
            fields=[
                ('mtl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cfetp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cfetp')),
                ('workcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.workcenter')),
            ],
            options={
                'db_table': 'MTL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('skill_level', models.IntegerField(choices=[(3, 'Apprentice'), (5, 'Journeyman'), (7, 'Craftsman'), (9, 'Superintendent')])),
                ('afsc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.afsc')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ranks')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.roles')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workcenter')),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ITP',
            fields=[
                ('itp_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('trainer_signature', models.BooleanField(blank=True, default=False, null=True)),
                ('trainee_signature', models.BooleanField(blank=True, default=False, null=True)),
                ('mtl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.mtl')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_itps', to='core.users')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itp_trainer_set', to='core.users')),
            ],
            options={
                'db_table': 'ITP',
                'managed': True,
            },
        ),
    ]
