# Generated by Django 5.2.2 on 2025-06-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cfetp_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itp',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
