# Generated by Django 5.2.2 on 2025-06-25 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itp_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itp',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainee_itps', to='core.users'),
        ),
        migrations.AlterField(
            model_name='itp',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itp_trainer_set', to='core.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
